#!/usr/bin/env python

'''
Activate the generic bash-completion script for the argcomplete module.
'''

import os, sys, argparse, pkg_resources
parser = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)

parser.add_argument("--dest", help="Specify the destination directory", default="/etc/bash_completion.d")
parser.add_argument("--user", help="Install into user directory (~/.bash_completion.d/)", action='store_true')
args = parser.parse_args()

if args.user:
    args.dest = os.path.expanduser("~/.bash_completion.d/")

if not os.path.exists(args.dest):
    parser.error("Path {d} does not exist".format(d=args.dest))

args.dest = os.path.join(args.dest, "python-argcomplete.sh")

print "Installing bash completion script", args.dest

with pkg_resources.resource_stream("argcomplete", "resources/python-argcomplete.sh") as in_fh, open(args.dest, 'w') as out_fh:
    out_fh.write(in_fh.read())
